#!/usr/bin/python3
# -*- mode: python; coding: utf-8 -*-
"""
Usage: ubyte [OPTIONS]

optional arguments:
  -h, --help         show this help message and exit
  -v, --version      show version information and exit
  -c, --copyright    show copying policy and exit
  -i, --iso-8859-15  use ISO-8859-15 rather than Latin-1
"""
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose.  See the GNU General Public License for  #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

import sys
import pathlib
import argparse

try:
    from locale import (Error, setlocale, LC_ALL)
    _ = setlocale(LC_ALL, '')
except (ImportError, ModuleNotFoundError, NameError, Error):
    pass

__author__ = 'Klaus Alexander Seistrup <klaus@seistrup.dk>'
__revision__ = '2017-04-02'
__version__ = '1.1.0 ({})'.format(__revision__)
__copyright__ = """\
ubyte {}
Copyright © 1999-2017 Klaus Alexander Seistrup <klaus@seistrup.dk>

This is free software; see the source for copying conditions.  There is no
warranty; not even for merchantability or fitness for a particular purpose.\
""".format(__version__)

(BOLD, PLAIN) = ('\x1b[1m', '\x1b[0m') if sys.stdout.isatty() else ('', '')


def leader(idx):
    """Construct a row leader"""
    return '{}{:02X}{}'.format(BOLD, idx, PLAIN)


def itoa(i, latin15=False):
    """Convert an int to the corresponding unicode/iso-8859-15 char"""
    if latin15:
        char = i.to_bytes(1, sys.byteorder).decode('iso-8859-15')
    else:
        char = chr(i)
    return char if char.isprintable() else '\N{LIGHT SHADE}'


def ubyte(latin15=False):
    """Show a fancy character table {0‥255}"""
    print('\t   {}0123456789ABCDEF{}'.format(BOLD, PLAIN) * 2)
    for upper in range(0x00, 0x80, 0x10):
        (lolead, loline) = (leader(upper), [])
        (uplead, upline) = (leader(upper + 0x80), [])
        for lower in range(0x10):
            loline.append(itoa(upper + lower, latin15))
            upline.append(itoa(upper + lower + 0x80, latin15))
        print('\t{} {}'.format(lolead, ''.join(loline)), end='')
        print('\t{} {}'.format(uplead, ''.join(upline)))


def main(progname='ubyte'):
    """Main entry point"""

    parser = argparse.ArgumentParser(
        prog=progname,
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s/' + __version__,
                        help='show version information and exit')
    parser.add_argument('-c', '--copyright', action='version',
                        version=__copyright__,
                        help='show copying policy and exit')
    parser.add_argument('-i', '--iso-8859-15', action='store_true',
                        help='use ISO-8859-15 rather than Latin-1')

    args = parser.parse_args()

    ubyte(args.iso_8859_15)

    return 0


if __name__ == '__main__':
    sys.exit(main(pathlib.Path(sys.argv[0]).name))

# eof
